apiVersion: v1
kind: Service
metadata:
  labels:
    app: nacos
  name: nacos
  namespace: nwu
spec:
  ports:
  - port: 8848
    name: nacos
    protocol: TCP
    targetPort: 8848
    nodePort: 10016
  selector:
    app: nacos
  type: NodePort
			