apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nacos
  name: nacos
  namespace: nwu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  strategy: {}
  template:
    metadata:
      labels:
        app: nacos
    spec:
#      nodeName: master-03
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/rian_ns/nwu_projects:nacosv1.3.2
        name: nacos
        imagePullPolicy: Always
        ports:
        - containerPort: 8848
#        envFrom:
#        - configMapRef:
#          name: nacos
