apiVersion: v1
kind: Service
metadata:
  labels:
    app: wenwuzhengji
  name: wenwuzhengji
  namespace: nwu
spec:
  ports:
  - port: 8085
    name: wenwuzhengjiback
    protocol: TCP
    targetPort: 8085
    nodePort: 10008
  - port: 3010
    name: wenwuzhengjifront
    protocol: TCP
    targetPort: 3010
    nodePort: 10007
  selector:
    app: wenwuzhengji
  type: NodePort
