apiVersion: v1
kind: Service
metadata:
  labels:
    app: yonghuzhenbie
  name: yonghuzhenbie
  namespace: nwu
spec:
  ports:
  - port: 8082
    name: yonghuzhenbieback
    protocol: TCP
    targetPort: 8082
    nodePort: 10004
  - port: 3000
    name: yonghuzhenbiefront
    protocol: TCP
    targetPort: 3000
    nodePort: 10003
  selector:
    app: yonghuzhenbie
  type: NodePort
