apiVersion: v1
kind: Service
metadata:
  labels:
    app: yunguan
  name: yunguan
  namespace: nwu
spec:
  ports:
  - port: 10017
    name: yunguan
    protocol: TCP
    targetPort: 10017
    nodePort: 10017
  selector:
    app: yunguan
  type: NodePort
