apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weifuwu-menhu
  name: weifuwu-menhu
  namespace: nwu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weifuwu-menhu
  strategy: {}
  template:
    metadata:
      labels:
        app: weifuwu-menhu
    spec:
#      nodeName: master-03
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/rian_ns/nwu_projects:weifuwu-menhuv1.0
        name: weifuwu-menhu
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
