apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weifuwu-nacos
  name: weifuwu-nacos
  namespace: nwu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weifuwu-nacos
  strategy: {}
  template:
    metadata:
      labels:
        app: weifuwu-nacos
    spec:
#      nodeName: master-03
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/rian_ns/nwu_projects:weifuwu-nacosv1.3.2
        name: weifuwu-nacos
        imagePullPolicy: Always
        ports:
        - containerPort: 8848
#        envFrom:
#        - configMapRef:
#            name: nacos
