apiVersion: v1
kind: Service
metadata:
  labels:
    app: weifuwu-redis
  name: weifuwu-redis
  namespace: nwu
spec:
  ports:
  - port: 6379
    name: weifuwu-redis
    protocol: TCP
    targetPort: 6379
    nodePort: 6379
  selector:
    app: weifuwu-redis
  type: NodePort
=