apiVersion: v1
kind: Service
metadata:
  labels:
    app: weifuwu-nacos
  name: weifuwu-nacos
  namespace: nwu
spec:
  ports:
  - port: 8848
    name: weifuwu-nacos
    protocol: TCP
    targetPort: 8848
    nodePort: 10018
  selector:
    app: weifuwu-nacos
  type: NodePort
