apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weifuwu-collectionoutmanagement
  name: weifuwu-collectionoutmanagement
  namespace: nwu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weifuwu-collectionoutmanagement
  strategy: {}
  template:
    metadata:
      labels:
        app: weifuwu-collectionoutmanagement
    spec:
#      nodeName: master-03
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/rian_ns/nwu_projects:weifuwu-collectionoutmanagementv1.0
        name: weifuwu-collectionoutmanagement
        imagePullPolicy: Always
        ports:
        - containerPort: 8023
#        envFrom:
#        - configMapRef:
#            name: nacos
